// English source copy for the family-camping deep dive. Facts verified 2026-10-09
// (see CHANGE_LOG for sources). Translations are generated from this object.
export default {
  meta: {
    title: 'Best Family Camping Near San Luis Potosí: 9 Places Worth the Drive (2026)',
    discover_title: 'Warm springs, a volcanic crater and ghost-rock forests',
    excerpt: 'From a warm spring-fed lagoon to a campsite inside a volcanic crater: the best family camping within about two hours of San Luis Potosí, with 2026 prices, facilities, seasons and honest safety notes.',
    meta_title: 'Family Camping Near San Luis Potosí: 9 Best Spots (2026)',
    meta_description: 'The best family campsites near SLP city: Media Luna, Sierra de Álvarez, Cráter Encantado and more, with 2026 prices, bathrooms, fire rules, seasons and road-safety tips.',
  },
  ui: {
    quickAnswerLabel: 'Quick Answer',
    tocTitle: 'In This Deep Dive',
    readingTime: 'Estimated reading time: 18 minutes · Updated October 2026',
    photo: 'Photo',
    coverPhoto: 'Cover photo',
    factLabels: { drive: 'Drive from SLP', cost: 'Camping cost', facilities: 'Facilities', bestFor: 'Best for', season: 'Best season', google: 'Google rating', contact: 'Contact' },
    tableHeaders: ['Place', 'Drive', 'Camping cost', 'Bathrooms', 'Best for'],
    leftOutHeaders: ['Place', 'Why it’s not on the list'],
    takeawaysTitle: 'Key Takeaways',
    proTipsTitle: 'Pro Tips for Camping Around SLP',
    faqTitle: 'Frequently Asked Questions',
    relatedTitle: 'Related Reading',
    sourcesTitle: 'Sources',
  },
  quickAnswer: 'For most families, the best camping near San Luis Potosí is <strong>Laguna de la Media Luna</strong> in Rioverde (about 2 h 15 min): warm spring water, 24-hour bathrooms and tent camping for MXN 150 per tent plus entry. Closer to the city, <strong>Sierra de Álvarez</strong> (about 45 min) offers cool pine-oak forest with private campsites, and <strong>Cráter Encantado</strong> in Armadillo (about 1 h) lets kids camp inside a volcanic crater.',
  toc: [
    ['how-we-chose', 'How these places were chosen'],
    ['at-a-glance', 'All 9 places at a glance'],
    ['media-luna', '1. Laguna de la Media Luna'],
    ['shamballa', '2. Shamballa, Sierra de Álvarez'],
    ['crater-encantado', '3. Cráter Encantado, Armadillo'],
    ['colibri', '4. Colibrí Campsite'],
    ['valle-fantasmas', '5. Valle de los Fantasmas'],
    ['realejo', '6. El Realejo, Guadalcázar'],
    ['la-mision', '7. Campamento La Misión'],
    ['guided', '8. Guided camping with Corazón de Xoconostle'],
    ['puente-de-dios', '9. Long-weekend upgrade: Puente de Dios'],
    ['left-out', 'Places left off the list'],
    ['seasons', 'When to go: weather, cold nights and rain'],
    ['safety', 'Safety on the road and at camp'],
    ['fire', 'Fire rules and leaving no trace'],
    ['packing', 'What to pack'],
    ['faq', 'FAQ'],
  ],
  hook: '<strong>San Luis Potosí sits on a high plateau ringed by sierras, desert and warm springs</strong>, which means a family camping trip can look completely different depending on which direction you drive. Head east and you hit pine forest and frosty mornings. Keep going and you reach a turquoise lagoon that stays warm all year. Turn north and you are in open desert under some of the darkest skies in central Mexico.',
  intro: [
    'That variety is the good news. The less good news is that reliable, up-to-date information about where families can actually camp is scattered across Facebook pages, old blog posts and contradictory news articles. Prices change, campsites close after a rainy season, and some places that look perfect on Instagram turn out to have no bathrooms and a 10-kilometre dirt road.',
    'This guide pulls it together. It focuses on places that suit families with children: somewhere safe to pitch a tent, bathrooms within reach, and something for kids to do once the tent is up.',
  ],
  howWeChose: {
    title: 'How these places were chosen',
    subtitle: 'More than 40 candidates, narrowed to the nine that families can actually use in 2026',
    paragraphs: [
      'More than 40 campgrounds, parks and ecotourism sites within roughly three hours of the city were compared. Each one was checked against official sources (CONANP protected-area pages, state and municipal tourism information, the parks’ own websites), recent coverage in local media such as <em>Plano Informativo</em>, <em>El Universal San Luis</em> and <em>El Sol de San Luis</em>, and recent Google reviews read for current conditions, prices and red flags.',
      'Only places that are operating in 2026 and that allow overnight tent camping made the list. Where a price or rule could only be confirmed from an older source or a single review, that is stated next to it. Treat every price as a guide and confirm by WhatsApp before you go: small campgrounds around SLP change rates without updating their pages.',
    ],
    callout: 'Drive times are measured from the Plaza de Armas in the historic centre and assume no traffic. On mountain and dirt roads, add 15–30%.',
  },
  atAGlance: {
    title: 'All 9 places at a glance',
    subtitle: 'Compare drive time, cost and comfort before you dig into the details',
    rows: [
      ['Laguna de la Media Luna', '~2 h 15 min', 'MXN 150/tent + entry', '24 h, showers', 'Swimming, all ages'],
      ['Shamballa, Sierra de Álvarez', '~45–55 min', '~MXN 300 (unit unclear)', 'Yes, hot water', 'First-timers, cold-weather comfort'],
      ['Cráter Encantado, Armadillo', '~1 h', 'MXN 300 adult / 200 child', 'Yes (basic)', 'Kids who need activities'],
      ['Colibrí Campsite', '~45 min', 'Ask by WhatsApp', 'Yes, clean', 'Quiet private weekend'],
      ['Valle de los Fantasmas', '~45 min', 'Small community fee', 'Assume none', 'Adventurous families'],
      ['El Realejo, Guadalcázar', '~1 h 30 min', '~MXN 50/person (2023)', 'Yes (rustic)', 'Rock formations, stargazing'],
      ['Campamento La Misión', '~1 h 5 min', 'Ask by phone', 'One', 'Dark skies, calm families'],
      ['Corazón de Xoconostle (guided)', 'Pickup in SLP', 'Package price', 'Depends on trip', 'No gear, no experience'],
      ['Puente de Dios, Tamasopo', '~3 h 30 min', 'Entry MXN 150', 'Yes', 'Long weekend, strong swimmers'],
    ],
  },
  places: {
    mediaLuna: {
      title: '1. Laguna de la Media Luna (Rioverde)',
      subtitle: 'The best all-round family camping in range, thanks to warm spring water and real facilities',
      paragraphs: [
        'If you only make one camping trip from San Luis Potosí, make it this one. The Media Luna is a crescent-shaped lagoon fed by thermal springs in the municipality of Rioverde, with crystal-clear water that recent visitors measure at around 28 °C. That temperature is the whole point: kids can swim, float and snorkel in the morning before the sun is high, and again in the evening, any month of the year.',
        'Rioverde sits much lower and warmer than SLP city, so this is also the easiest place to camp in winter without freezing gear. Shallow edges, shade trees and green lawns make it manageable with small children, and life jackets are mandatory in most swimming zones (rental is MXN 50). There is a food court on site, and the spring itself is famous for the mammoth fossils divers have found on its bed; some finds are shown at the museum in Rioverde town, about 15 km away.',
        'The camping area is a designated zone within the state park. The ejido that manages the site banned camping right next to the water back in 2020, and camping now runs in its own area, so don’t expect to pitch a tent on the shore.',
      ],
      fact: [
        ['drive', 'About 136 km / 2 h 15 min via Highway 70 or the Rioverde toll road. Paved to the gate; large parking lot.'],
        ['cost', 'Tent MXN 150 plus entry (adults MXN 100, children and seniors MXN 50). Cabins MXN 1,300–2,600 per night with entry included. Cash only.'],
        ['facilities', 'Bathrooms open 24 h, showers until 19:00, food court, kayak and raft rental. No cell signal and weak Wi-Fi.'],
        ['bestFor', 'Families with kids of any age who want to swim.'],
        ['season', 'October–May. Summer rains can cloud the water and have closed the park before (for about 10 days in late July–early August 2024). Closed Tuesdays; day hours 8:00–17:00.'],
        ['google', '4.6★ from 12,486 reviews'],
        ['contact', 'Cabin reservations by WhatsApp 487 101 5874'],
      ],
      grillCallout: 'Older coverage disagreed on grills (<em>El Universal</em> 2025 listed them as banned; <em>Milenio</em> 2025 listed them as a facility), but in September 2026 the park listed uncooked food as prohibited and allowed only ready-made food. Plan on cold food and the food court, and ask by WhatsApp before you pack any charcoal. Soap and shampoo are never allowed in the springs.',
    },
    shamballa: {
      title: '2. Shamballa Estancia Campestre (Sierra de Álvarez)',
      subtitle: 'The closest comfortable option: forest camping with bathrooms, hot water and a shared kitchen',
      paragraphs: [
        'Forty-five minutes east of the city on Highway 70, the road climbs into the Sierra de Álvarez, a federally protected area of pine and oak forest. Shamballa is a fenced, staffed property near Ejido San Francisco in Villa de Zaragoza, with a campsite, rustic cabins (one with a fireplace) and a common area with a shared kitchen and fire rings.',
        'It is the best choice for a first family camping trip: close enough to drive home if it all goes wrong, with bathrooms and hot water so the experiment doesn’t end in tears. Reviewers describe the property as safe and the forest as cool and quiet, and the trails of the Valle de los Fantasmas are minutes away for a morning walk. There is no water to swim in.',
      ],
      fact: [
        ['drive', 'About 46 km / 45–55 min via the free Highway 70. The entrance is on a curve and easy to miss.'],
        ['cost', 'About MXN 300 for camping, including bathrooms, fire rings and the shared kitchen (November 2025 review). It is not clear whether that is per tent or per person, so ask. Cabin prices on request.'],
        ['facilities', 'Bathrooms, hot water, shared kitchen, fire rings, cabins, gardens.'],
        ['bestFor', 'First-time campers and anyone who wants forest without roughing it.'],
        ['season', 'October–May. Nights from November to February are cold: bring winter sleeping bags.'],
        ['google', '4.5★ from 158 reviews'],
        ['contact', '444 460 4578 · 444 175 3424 · Facebook: Shamballaestanciacampestre'],
      ],
    },
    crater: {
      title: '3. Cráter Encantado Ecoparque (Armadillo de los Infante)',
      subtitle: 'Camp inside a volcanic crater, with the best kids’ activities near SLP',
      paragraphs: [
        'Cráter Encantado is an ecopark about 10 minutes beyond the old mining town of Armadillo de los Infante, roughly an hour from the city. The headline is that you pitch your tent inside a volcanic crater. The reason families keep coming back is everything else: a zip line, archery, horse rides, mountain bikes, a kids’ circuit with hanging bridges and climbing walls, a “dinosaur bone” dig and a small farm with horses, deer and birds.',
        'That makes it the best pick for children who need a full programme to stay happy. The trade-offs come from recent reviews: some equipment and bathrooms have been poorly maintained, steps can be steep and slippery, and there is little shade at midday. Bring sun protection and check the kids’ gear yourself before they use it.',
      ],
      fact: [
        ['drive', 'About 53 km / 1 h, paved to Armadillo.'],
        ['cost', 'Entry MXN 100 adult / 50 child. Camping MXN 300 adult / 200 child, bring your own tent. Zip line MXN 350; “Experiencia Total” package (entry, archery, breakfast, zip line, horse ride and camping) MXN 1,350 adult / 1,200 child (park website, 2026). Activity prices have changed over the years, so confirm.'],
        ['facilities', 'Bathrooms, breakfast in packages, pet friendly. Showers and fire rules at the campsite not confirmed.'],
        ['bestFor', 'Kids who need a full programme of activities.'],
        ['season', 'Year-round on weekends and holidays (10:00–18:00); groups midweek by arrangement. Hot sun at midday, cold nights in winter.'],
        ['google', '4.6★ from 187 reviews'],
        ['contact', 'WhatsApp 444 492 4522 · craterencantado.com'],
      ],
    },
    colibri: {
      title: '4. Colibrí Campsite (Sierra de Álvarez)',
      subtitle: 'A small, private site in the forest for families who want quiet',
      paragraphs: [
        'Colibrí is the opposite of an ecopark: a small private campsite in Villa de Zaragoza, promoted as private and secure, with clean bathrooms, a fire pit with a grill and firewood supplied. There are no activities and usually no staff when you arrive. Instructions come by WhatsApp, so read them before you lose signal.',
        'It suits families who want a quiet weekend in the trees with forest trails nearby. Two practical notes from reviewers: the firewood is left under the grill and can get wet if it rains, and local dogs will raid any food left out, so keep coolers closed and food in the car.',
      ],
      fact: [
        ['drive', 'About 42 km / 45 min via Highway 70.'],
        ['cost', 'Not published. Ask on WhatsApp.'],
        ['facilities', 'Clean bathrooms, parking, fire pit and grill, firewood. Showers and drinking water not confirmed.'],
        ['bestFor', 'A calm weekend for one or two families.'],
        ['season', 'October–May; cold nights in winter.'],
        ['google', '4.8★ from 10 reviews (a small sample)'],
        ['contact', 'WhatsApp 444 652 5715 · TikTok @colibri.campsite'],
      ],
    },
    valle: {
      title: '5. Valle de los Fantasmas (Sierra de Álvarez protected area)',
      subtitle: 'Strange rock formations, dark skies and primitive camping run with the local ejido',
      paragraphs: [
        'The Valle de los Fantasmas (“Valley of the Ghosts”) owes its name to the pale rock formations that rise out of the forest: the Elephant Rock, the Piedra Flotante that seems to balance on nothing. It lies inside the Sierra de Álvarez Flora and Fauna Protection Area, a federal reserve of about 16,900 hectares where CONANP lists camping as a permitted activity. Wildlife here includes white-tailed deer, and CONANP has even recorded a puma on camera traps (2017).',
        'Camping zones are signposted and managed with the community of Ejido San Francisco, where local women also offer guided walks and traditional meals. Access is a small “symbolic” fee whose current amount couldn’t be confirmed. CONANP notes there is no lodging or food inside the protected area, so assume no bathrooms or water and bring everything.',
        'This is a place for adventurous families comfortable with primitive camping, or for pairing with Shamballa or Colibrí: sleep there, spend the day here. Much of the land around the rock formations is fenced private or ejido property, and map apps get confused, so ask locals in San Francisco or hire a local guide.',
      ],
      fact: [
        ['drive', 'About 44 km / 45 min via Highway 70 toward Rioverde.'],
        ['cost', 'Small community access fee (amount unconfirmed for 2026).'],
        ['facilities', 'Signposted camping zones and interpretive trails. Assume no bathrooms, water or electricity. Weekend gorditas at the roadside pines.'],
        ['bestFor', 'Families with camping experience; stargazing.'],
        ['season', 'October–May. Frost is possible in winter; CONANP suggests Easter as a good time to visit.'],
        ['google', '4.7★ from 134 reviews (protected-area listing)'],
        ['contact', 'Ask in Ejido San Francisco on arrival'],
      ],
    },
    realejo: {
      title: '6. El Realejo, Guadalcázar (Camping La Casa del Tío)',
      subtitle: 'Giant rocks, desert ponds and some of the darkest skies within two hours of the city',
      paragraphs: [
        'North of the city the landscape opens into the Altiplano, and around the old mining town of Guadalcázar it breaks into giant boulders, caves and small ponds. El Realejo sits inside the Guadalcázar state protected area, and Camping La Casa del Tío is a large, fenced private property with a rustic bathroom, water, electricity, grills, a small cabin and a dining area. Breakfasts (gorditas, eggs) and bundles of firewood can be ordered.',
        'Five minutes away, the rocks of Cerro Las Comadres make an easy family walk, and the area also offers horse riding, climbing and mountain biking. There is no cell signal, and mosquitoes arrive with the summer rains.',
      ],
      fact: [
        ['drive', 'About 96 km / 1 h 30 min. Highway 57 north to the km 75 turnoff, then through Guadalcázar.'],
        ['cost', 'About MXN 50 per person (2023 review; may have changed).'],
        ['facilities', 'Rustic bathroom, water, electricity, grills, small cabin, dining area. No cell signal.'],
        ['bestFor', 'Rock scrambling, desert landscapes, stargazing.'],
        ['season', 'October–April: warm days, cold winter nights.'],
        ['google', '4.9★ from 15 reviews'],
      ],
      safetyCallout: 'The route uses Highway 57 north. In 2026 the stretch around <strong>Matehuala</strong>, much farther north, was the most-flagged corridor in local and national coverage, including a kidnapping in March 2026. The km 75 turnoff is well south of that zone. Drive in daylight and don’t continue north.',
    },
    mision: {
      title: '7. Campamento La Misión (Armadillo de los Infante)',
      subtitle: 'A quiet desert campsite with superb night skies, for families who bring everything',
      paragraphs: [
        'La Misión is a small fenced campsite in the desert near Armadillo run by its host, Don Salvador. It has a camping area, two vaulted rooms, grills and mesquite firewood, and guests can use the owner’s kitchen. Reviewers praise the calm, the safety and above all the night sky.',
        'It is deliberately simple. There is only one bathroom, no food or drinks for sale, no cell signal and no gas station nearby, so arrive with a full tank and every meal planned. It is not a party place: loud music and heavy drinking are not welcome, which is exactly why families like it.',
      ],
      fact: [
        ['drive', 'About 58 km / 1 h 5 min; the last stretch is a short dirt road that small cars manage.'],
        ['cost', 'Not published. Ask by phone.'],
        ['facilities', 'One bathroom, grills, firewood, use of the owner’s kitchen, two rooms. No signal, no shop.'],
        ['bestFor', 'Calm families, stargazing, dogs welcome.'],
        ['season', 'October–April.'],
        ['google', '5.0★ from 27 reviews'],
        ['contact', '444 457 3889'],
      ],
    },
    guided: {
      title: '8. Guided camping with Corazón de Xoconostle',
      subtitle: 'For families with no gear and no experience',
      paragraphs: [
        'Corazón de Xoconostle is not a campground but an outdoor operator based in the Barrio de San Miguelito in the city. It runs guided overnight camping at its trekking destinations, including Armadillo de los Infante, the Sierra de Álvarez, the Sierra de San Miguelito and Guadalcázar, with NOM-certified guides. Ask whether tents and sleeping bags are included: if they are, it is the easiest way to try camping without buying gear first.',
        'Package prices are set per trip, so ask for a quote. For more about the company, see our <a href="/blog/corazon-de-xoconostle">profile of Corazón de Xoconostle</a>.',
      ],
      contact: 'Phone/WhatsApp 444 657 1872 · corazondexoconostle.com',
    },
    puente: {
      title: '9. Long-weekend upgrade: Puente de Dios (Tamasopo)',
      subtitle: 'Turquoise pools in the Huasteca, but too far for a regular weekend',
      paragraphs: [
        'Puente de Dios in Tamasopo is one of the most beautiful swimming spots in the state: turquoise pools under a natural rock bridge at the gateway to the Huasteca Potosina. At about 3 h 30 min from the city it is beyond the range of this guide, so treat it as a long-weekend trip. Entry is MXN 150 (2026), with life jackets at about MXN 25 and parking at MXN 30.',
        'Two cautions for families: there are a few hundred steep steps down to the water, and the current can be strong, so it suits children of eight and up who swim well. The Huasteca stretch of Highway 70 calls for daylight driving. Our <a href="/blog/huasteca-potosina-itinerary-2026">Huasteca Potosina itinerary</a> covers the region in depth.',
      ],
    },
  },
  leftOut: {
    title: 'Places left off the list (and why)',
    subtitle: 'Some well-known names didn’t make the cut for families in 2026',
    rows: [
      ['Parque Nacional El Gogorrón', 'Camping is allowed, but there are no services at all: wild camping only.'],
      ['Presa de San José and Sierra de San Miguelito', 'Great for day hikes and picnics; no established campground with services.'],
      ['Raíces Ecopark and Fisterra Glamping', 'Very rough access roads, plus 2025–2026 reviews reporting dirty glamping tents and food stolen at a cabin.'],
      ['Parque Recreativo Gogorrón', 'Thermal pools with cabins, but 2026 reviews report poor maintenance and no tent camping could be confirmed.'],
      ['Real de Catorce campsites', 'Three and a half to four hours away, and the route passes Matehuala on Highway 57.'],
    ],
    note: 'Looking for a structured camp for older kids instead? Tlachtli in the Sierra de Álvarez has run inclusion- and conservation-focused camps since 1996 with schools and groups.',
  },
  seasons: {
    title: 'When to go: weather, cold nights and rain',
    subtitle: 'Altitude matters more than the calendar',
    paragraphs: [
      'San Luis Potosí city sits at about 1,860 metres, and the Sierra de Álvarez campsites are higher still. In the city, average January lows are around 5.5 °C, with record lows below freezing. In the sierra and the Altiplano deserts around Armadillo and Guadalcázar, <strong>near-freezing or frosty nights are normal from November to February</strong>, even after warm, sunny days.',
      'The rainy season runs from roughly May or June to October, with the wettest months in June, July and September. Expect afternoon storms, muddy dirt roads and springs that can turn cloudy: Media Luna closed in the summer of 2024 after heavy rain muddied the spring. Never camp in a dry arroyo, which can flash-flood.',
      'The sweet spots are <strong>late October–November</strong> and <strong>March–April</strong>: dry, mild days and manageable nights. December to February works if you have real cold-weather gear. Easter and long weekends bring crowds, especially at Media Luna, so reserve ahead.',
    ],
  },
  safety: {
    title: 'Safety on the road and at camp',
    subtitle: 'An honest look at the risks, without the alarmism',
    paragraphs: [
      'The US State Department rates San Luis Potosí state at Level 2, “exercise increased caution” (May 2026). For campers, the risk that shows up in 2026 coverage is on certain highways rather than at the campsites: Highway 57 north toward Matehuala and the Huasteca stretch of Highway 70 were the corridors most flagged by local and national media. Armed robberies were also reported on Highway 70 toward Rioverde in 2023. No 2025–2026 incidents specific to the Sierra de Álvarez, Armadillo or Guadalcázar campsites in this guide turned up.',
      'In practice: drive in daylight, use toll roads where they exist, don’t stop on isolated stretches, and arrive before dark. Several of these sites have no phone signal, so download offline maps and tell someone your plan. Most campsites only take cash.',
    ],
  },
  fire: {
    title: 'Fire rules and leaving no trace',
    subtitle: 'Wildfire season is long, and 2026 was a bad year',
    paragraphs: [
      'San Luis Potosí’s critical wildfire season runs from 16 January to 30 June. In 2026, around 23,500 hectares had burned by early July, and officials attribute nearly all fires to human causes. In the protected areas (Sierra de Álvarez, Sierra de San Miguelito, Gogorrón), CONANP only allows fires in designated spots.',
      'Use the campground’s own fire ring, keep water at hand, drown the fire completely before bed and never burn rubbish. Pack out everything you bring in.',
    ],
  },
  proTips: [
    ['Pack for 0 °C, even in spring', 'Sleeping bags rated to 0 °C or lower, wool layers, hats and insulated sleeping pads. Desert and sierra nights drop fast after sunset.'],
    ['Lock the cooler', 'Free-roaming ranch dogs raid food at several sites. Keep food in the car overnight.'],
    ['Carry cash and a full tank', 'Most campsites don’t take cards, and some (like La Misión) have no gas station nearby.'],
    ['Respect the springs', 'Life jackets are mandatory at Media Luna (MXN 50 rental; you can’t bring your own) and at Puente de Dios (around MXN 25). Bring water shoes and leave the soap at home.'],
    ['Shake out your boots', 'Scorpions and snakes live in the desert sites. Bring a headlamp and insect repellent for the rainy season.'],
    ['Confirm by WhatsApp', 'Prices and rules at small campsites change often. A two-minute message saves a wasted drive.'],
  ],
  takeaways: [
    'Media Luna is the best all-round family pick: warm water, 24 h bathrooms, MXN 150 per tent plus entry.',
    'For a first trip close to the city, Shamballa in the Sierra de Álvarez is 45 minutes away with hot water and a shared kitchen.',
    'Cráter Encantado has the most for kids to do; Valle de los Fantasmas and La Misión are for families who want quiet and stars.',
    'Plan for near-freezing nights from November to February, and avoid the June–September rains.',
    'Drive in daylight, carry cash, and confirm prices by WhatsApp before you go.',
  ],
  faq: [
    ['Where can I camp near San Luis Potosí with kids?', 'The best family options are Laguna de la Media Luna in Rioverde (warm springs, 24 h bathrooms), Shamballa and Colibrí in the Sierra de Álvarez (about 45 minutes), and Cráter Encantado in Armadillo de los Infante (activities for kids, camping inside a volcanic crater).'],
    ['How much does it cost to camp at the Media Luna?', 'As of February 2026, camping costs MXN 150 per tent plus entry (MXN 100 adults; MXN 50 children and seniors). Cabins cost MXN 1,300–2,600 per night with entry included. The park is closed on Tuesdays.'],
    ['Is it cold to camp near San Luis Potosí?', 'Yes, from November to February. The city sits at about 1,860 m and the sierras are higher, so near-freezing nights are normal. Media Luna in Rioverde is lower and much warmer.'],
    ['Can I make a campfire?', 'Only in designated fire rings. Wildfire season runs from 16 January to 30 June, and protected areas such as the Sierra de Álvarez only allow fires in designated spots. Media Luna allows only ready-made food (no cooking on site as of September 2026); ask before you go.'],
    ['Is it safe to camp near San Luis Potosí?', 'Our news search found no 2025–2026 incident reports specific to the campsites in this guide. The main risk is on certain highways, especially Highway 57 near Matehuala. Drive in daylight, use toll roads and arrive before dark.'],
    ['Do I need a reservation?', 'For cabins at Media Luna and for private campsites such as Colibrí, Cráter Encantado and Shamballa, yes: message them by WhatsApp. At Valle de los Fantasmas you pay a small community fee on arrival.'],
  ],
  related: [
    ['/blog/best-hikes-san-luis-potosi', 'The Best Hikes in San Luis Potosí', 'Trails in the same sierras, from easy family loops to summit days'],
    ['/blog/day-trips-from-san-luis-potosi-2026', 'Day Trips from San Luis Potosí', 'Ideas for when you’d rather sleep in your own bed'],
    ['/blog/best-parks-for-kids-san-luis-potosi', 'Best Parks for Kids in San Luis Potosí', 'Closer-to-home outdoor time with children'],
    ['/blog/huasteca-potosina-itinerary-2026', 'Huasteca Potosina Itinerary', 'For the long weekend: waterfalls, rivers and Puente de Dios'],
  ],
  captions: {
    mediaLunaLagoon: 'The Media Luna’s spring-fed water stays warm all year, which is what makes winter camping here easy.',
    mediaLunaPool: 'Swimmers at the Media Luna. Life jackets are mandatory in most zones.',
    armadillo: 'Armadillo de los Infante, the old mining town near Cráter Encantado and La Misión.',
    valle: 'The Sierra de Álvarez near the Valle de los Fantasmas: pine-oak forest about 45 minutes from the city.',
    valleRocks: 'Limestone and agaves in the Valle de los Fantasmas.',
    guadalcazar: 'The open country around Guadalcázar, on the way to El Realejo.',
    guadalcazarWater: 'One of the small desert reservoirs near Guadalcázar.',
    cold: 'Fog and frost are part of winter camping in the sierras around SLP.',
  },
};
