import type { SitemapEntry } from './locale';

type StaticRoute = Omit<SitemapEntry, 'lastmod'>;

/**
 * Static routes that don't come from Supabase. Keep this list in sync with
 * the page files actually under src/pages and intentionally indexed.
 * Pages disallowed in robots.txt or marked noIndex must NOT appear here.
 */
export const STATIC_ROUTES: StaticRoute[] = [
  { path: '/',                                        changefreq: 'weekly',  priority: 1.0 },
  { path: '/about',                                   changefreq: 'monthly', priority: 0.8 },
  { path: '/contact',                                 changefreq: 'monthly', priority: 0.7 },
  { path: '/faq',                                     changefreq: 'monthly', priority: 0.6 },
  { path: '/privacy',                                 changefreq: 'yearly',  priority: 0.3 },
  { path: '/terms',                                   changefreq: 'yearly',  priority: 0.3 },
  { path: '/cookies',                                 changefreq: 'yearly',  priority: 0.3 },
  { path: '/advertise',                               changefreq: 'monthly', priority: 0.6 },
  { path: '/services',                                changefreq: 'monthly', priority: 0.7 },
  { path: '/community',                               changefreq: 'monthly', priority: 0.6 },
  { path: '/places',                                  changefreq: 'daily',   priority: 0.9 },
  { path: '/events/all',                              changefreq: 'daily',   priority: 0.9 },
  { path: '/events/this-week',                        changefreq: 'daily',   priority: 0.9 },
  { path: '/blog',                                    changefreq: 'daily',   priority: 0.9 },
  { path: '/brands',                                  changefreq: 'weekly',  priority: 0.8 },
  { path: '/restaurants',                             changefreq: 'weekly',  priority: 0.8 },
  { path: '/cultural',                                changefreq: 'monthly', priority: 0.8 },
  { path: '/cultural-attractions',                    changefreq: 'monthly', priority: 0.8 },
  { path: '/cultural-tours',                          changefreq: 'monthly', priority: 0.7 },
  { path: '/cultural/history',                        changefreq: 'monthly', priority: 0.7 },
  { path: '/cultural/festivals',                      changefreq: 'monthly', priority: 0.7 },
  { path: '/cultural/music-dance',                    changefreq: 'monthly', priority: 0.7 },
  { path: '/cultural/culinary-traditions',            changefreq: 'monthly', priority: 0.7 },
  { path: '/cultural/customs-etiquette',              changefreq: 'monthly', priority: 0.7 },
  { path: '/cultural/religious-practices',            changefreq: 'monthly', priority: 0.7 },
  { path: '/outdoors',                                changefreq: 'monthly', priority: 0.8 },
  { path: '/parque-tangamanga',                       changefreq: 'monthly', priority: 0.7 },
  { path: '/parque-tangamanga-ii',                    changefreq: 'monthly', priority: 0.7 },
  { path: '/blog/factchecks',                         changefreq: 'weekly',  priority: 0.8 },
  { path: '/centro-historico',                        changefreq: 'monthly', priority: 0.7 },
  { path: '/traditional-cuisine',                     changefreq: 'monthly', priority: 0.7 },
  { path: '/family-friendly-activities',              changefreq: 'monthly', priority: 0.7 },
  { path: '/farmers-markets-san-luis-potosi',         changefreq: 'monthly', priority: 0.7 },
  { path: '/free-events-san-luis-potosi',             changefreq: 'monthly', priority: 0.8 },
  { path: '/food-festivals-san-luis-potosi',          changefreq: 'monthly', priority: 0.7 },
  { path: '/breakfast-spots-san-luis-potosi',         changefreq: 'monthly', priority: 0.7 },
  { path: '/weekend-getaways',                        changefreq: 'monthly', priority: 0.7 },
  { path: '/festival-primavera-2026',                 changefreq: 'weekly',  priority: 0.7 },
  { path: '/events/cara-sucia-country-fest-2026',     changefreq: 'weekly',  priority: 0.8 },
  { path: '/events/maraton-tangamanga-2026',          changefreq: 'weekly',  priority: 0.8 },
  { path: '/events/fenapo-2026',                      changefreq: 'weekly',  priority: 0.8 },
  { path: '/resources/expat-guide',                   changefreq: 'monthly', priority: 0.8 },
  { path: '/resources/living-guide',                  changefreq: 'monthly', priority: 0.8 },
  { path: '/resources/safety-guide',                  changefreq: 'monthly', priority: 0.8 },
  { path: '/resources/health-guide',                  changefreq: 'monthly', priority: 0.8 },
  { path: '/resources/family-guide',                  changefreq: 'monthly', priority: 0.8 },
  { path: '/resources/school-guide',                  changefreq: 'monthly', priority: 0.8 },
  { path: '/resources/arrival-checklist',             changefreq: 'monthly', priority: 0.8 },
  { path: '/resources/neighborhoods-san-luis-potosi', changefreq: 'monthly', priority: 0.8 },
  { path: '/guides/foodie-guide',                     changefreq: 'monthly', priority: 0.7 },
  { path: '/guides/potosino-wine-scene',              changefreq: 'monthly', priority: 0.7 },
  { path: '/digital-nomad-guide',                     changefreq: 'monthly', priority: 0.8 },
  { path: '/visit-san-luis-potosi',                   changefreq: 'monthly', priority: 0.8 },

  // Curated category landing pages (16 total) — added 2026-04-30 to fix
  // GSC "Discovered – currently not indexed" for these orphan URLs.
  { path: '/category/cantinas',                       changefreq: 'monthly', priority: 0.6 },
  { path: '/category/cocktail-bars',                  changefreq: 'monthly', priority: 0.6 },
  { path: '/category/easy-parking-spots',             changefreq: 'monthly', priority: 0.5 },
  { path: '/category/english-speaking-healthcare',    changefreq: 'monthly', priority: 0.7 },
  { path: '/category/family-activities',              changefreq: 'monthly', priority: 0.7 },
  { path: '/category/international-markets',          changefreq: 'monthly', priority: 0.6 },
  { path: '/category/language-exchange-cafes',        changefreq: 'monthly', priority: 0.6 },
  { path: '/category/live-music',                     changefreq: 'monthly', priority: 0.6 },
  { path: '/category/local-organic-products',         changefreq: 'monthly', priority: 0.6 },
  { path: '/category/open-for-breakfast',             changefreq: 'monthly', priority: 0.6 },
  { path: '/category/outdoors',                       changefreq: 'monthly', priority: 0.6 },
  { path: '/category/rainy-day-activities',           changefreq: 'monthly', priority: 0.6 },
  { path: '/category/remote-work-cafes',              changefreq: 'monthly', priority: 0.7 },
  { path: '/category/restaurants-with-playgrounds',   changefreq: 'monthly', priority: 0.6 },
  { path: '/category/sports-fitness',                 changefreq: 'monthly', priority: 0.6 },
  { path: '/category/terraces',                       changefreq: 'monthly', priority: 0.6 },

  // Service hub pages (10 total) — same fix.
  { path: '/san-luis-potosi-community-integration',   changefreq: 'monthly', priority: 0.7 },
  { path: '/san-luis-potosi-cultural-services',       changefreq: 'monthly', priority: 0.7 },
  { path: '/san-luis-potosi-experiences',             changefreq: 'monthly', priority: 0.7 },
  { path: '/san-luis-potosi-family-support',          changefreq: 'monthly', priority: 0.7 },
  { path: '/san-luis-potosi-home-services',           changefreq: 'monthly', priority: 0.7 },
  { path: '/san-luis-potosi-housing-services',        changefreq: 'monthly', priority: 0.7 },
  { path: '/san-luis-potosi-legal-administrative',    changefreq: 'monthly', priority: 0.7 },
  { path: '/san-luis-potosi-pet-care',                changefreq: 'monthly', priority: 0.7 },
  { path: '/san-luis-potosi-relocation-support',      changefreq: 'monthly', priority: 0.7 },
  { path: '/san-luis-potosi-wellness-services',       changefreq: 'monthly', priority: 0.7 },
];
