// English source copy for the best-hikes deep dive. Facts verified 2026-10-09
// (see CHANGE_LOG for sources). Translations are generated from this object.
export default {
  meta: {
    title: 'The 12 Best Hikes in San Luis Potosí: City Trails to Sierra Summits (2026)',
    discover_title: 'A rock window at 2,800 m, 70 minutes from downtown',
    excerpt: 'From easy loops in Tangamanga to the rock arch of La Ventana and the summit of Cerro del Potosí: the 12 best hikes in and around San Luis Potosí, with distances, elevation, fees and honest safety advice.',
    meta_title: 'Best Hikes in San Luis Potosí: 12 Trails Ranked (2026)',
    meta_description: 'The 12 best hikes in and around San Luis Potosí: La Ventana, Cerro del Potosí, Sendero del Capitán, Valle de los Fantasmas and more, with distance, elevation, fees and safety tips.',
  },
  ui: {
    quickAnswerLabel: 'Quick Answer',
    tocTitle: 'In This Deep Dive',
    readingTime: 'Estimated reading time: 20 minutes · Updated October 2026',
    photo: 'Photo',
    coverPhoto: 'Cover photo',
    factLabels: { trailhead: 'Trailhead', drive: 'Drive from SLP', stats: 'Distance and elevation', difficulty: 'Difficulty', fee: 'Fee', bestFor: 'Best for', google: 'Ratings', track: 'Track' },
    tableHeaders: ['Trail', 'Distance', 'Gain', 'Difficulty', 'Drive'],
    leftOutHeaders: ['Trail', 'Why it’s not on the list'],
    groupLabels: { easy: 'Easy', moderate: 'Moderate', hard: 'Hard' },
    takeawaysTitle: 'Key Takeaways',
    proTipsTitle: 'Pro Tips for Hiking Around SLP',
    faqTitle: 'Frequently Asked Questions',
    relatedTitle: 'Related Reading',
    sourcesTitle: 'Sources',
  },
  quickAnswer: 'The best hike near San Luis Potosí is <strong>La Ventana</strong>, a natural rock arch at about 2,800 m in the Sierra de San Miguelito (12 km round trip, hard, MXN 50 per person). For a big summit from the city, climb <strong>Cerro del Potosí</strong> (17.5 km). Families should start with <strong>Cañada del Lobo</strong> or <strong>Parque Tangamanga I</strong>, both free and 15 minutes or less from downtown.',
  toc: [
    ['how-we-chose', 'How these trails were chosen'],
    ['at-a-glance', 'All 12 hikes at a glance'],
    ['easy', 'Easy hikes in and near the city'],
    ['moderate', 'Half-day hikes'],
    ['hard', 'Big days for fit hikers'],
    ['worth-the-trip', 'Worth the trip: Real de Catorce'],
    ['left-out', 'Trails left off the list'],
    ['seasons', 'Altitude, seasons and water'],
    ['safety', 'Safety: what actually goes wrong'],
    ['rules', 'Rules in the protected areas'],
    ['guides', 'Hiking clubs and guides'],
    ['tips', 'Pro tips'],
    ['faq', 'FAQ'],
  ],
  hook: '<strong>In San Luis Potosí, the mountains start where the city ends.</strong> Drive to the end of Avenida Chapultepec in San Luis Potosí and the pavement simply stops at the foot of the Sierra de San Miguelito, a protected range of more than 111,000 hectares where trails climb to rock arches, summit crosses and views over the whole city.',
  intro: [
    'Look further and the options multiply: the pine-oak forest of the Sierra de Álvarez 50 minutes east, old mule paths between colonial mining towns, a dry volcanic crater on the Altiplano, and the sacred summits of Real de Catorce. The catch is that most of these trails are informal. Marking ranges from painted arrows to piles of stones, and the information online is scattered across Wikiloc tracks, Facebook groups and outdated blog posts.',
    'This guide ranks the 12 best hikes for 2026 and groups them by difficulty, with the numbers you need to plan: distance, elevation gain, fees, drive time and what to watch out for.',
  ],
  howWeChose: {
    title: 'How these trails were chosen',
    subtitle: 'More than 30 trails compared using GPS tracks, official sources and recent reviews',
    paragraphs: [
      'More than 30 trails in the city and within about two hours’ drive were compared. Distances and elevation come from the most-used public GPS tracks on Wikiloc and AllTrails (for example, the main La Ventana track has been recorded more than 550 times, and the Cerro del Potosí track more than 840). Rules and protected-area details come from CONANP, the official federal register (DOF) and the state parks agency, and fees and current conditions from recent hiker reviews and local media.',
      'GPS recorders disagree, so where sources differ the range is given. Fees at community-run trailheads change without notice; only the La Ventana fee could be confirmed in 2026, and the others are labelled with the year of the source.',
    ],
    callout: 'Watch the name: <strong>Cerro del Potosí</strong> in this guide is the roughly 2,650 m summit just south of SLP city. It is not the 3,700 m Cerro Potosí in Nuevo León.',
  },
  atAGlance: {
    title: 'All 12 hikes at a glance',
    subtitle: 'Sorted from easiest to hardest; drive times from the historic centre without traffic',
    rows: [
      ['Parque Tangamanga I', 'Up to 12.7 km (paved loop)', '~114 m', 'Easy', '5 min'],
      ['Cañada del Lobo', '3.5–7.1 km loops', '40–134 m', 'Easy', '12 min'],
      ['La Piedrota', '6–8.2 km', '~226 m', 'Easy–moderate', '15 min'],
      ['Cerro El Original', '2.3 km', '~240 m', 'Easy–moderate', '46 min'],
      ['Cueva de los Caballos', '~8 km loop or out-and-back', '240–330 m', 'Easy–moderate', '50 min'],
      ['Cráter Joya Honda', '5.1–5.8 km loop', '~240 m', 'Moderate', '65 min'],
      ['Sendero del Capitán', '~19 km one way (short options)', '~320 m up', 'Moderate–hard', '28 min'],
      ['Cerro Grande, Suspiro Picacho', '11.3–11.9 km', '540–600 m', 'Moderate–hard', '22 min'],
      ['La Ventana', '12.2–12.6 km', '~500 m', 'Hard', '~70 min'],
      ['Cerro del Potosí', '17.5–17.9 km', '765–970 m', 'Hard', '10 min'],
      ['Picacho del Fraile', '~15.6 km', '~960 m', 'Hard', '23 min'],
      ['Cerro del Quemado, Real de Catorce', '10.3–10.9 km', '365–410 m', 'Moderate (altitude)', '~3 h 30 min'],
    ],
  },
  groups: {
    easy: { title: 'Easy hikes in and near the city', subtitle: 'Free or almost free, close to home and good with kids' },
    moderate: { title: 'Half-day hikes', subtitle: 'A morning in real mountain terrain, with rock formations, forest and history' },
    hard: { title: 'Big days for fit hikers', subtitle: 'Long climbs, little shade and the best views in the region' },
    trip: { title: 'Worth the trip: Real de Catorce', subtitle: 'An overnight trip, not a day hike, but one of the most memorable walks in Mexico' },
  },
  trails: {
    tangamanga: {
      title: 'Parque Tangamanga I',
      paragraphs: [
        'Tangamanga I is a 420-hectare state park a few minutes from the centre, with a paved circuit of about 12.7 km around lakes and woodland, plus dirt paths you can mix in. It isn’t wilderness, but it is the best place to get used to the altitude before tackling the sierra, to run with a stroller, or to walk with grandparents. Entry is free; only sports facilities and events are charged.',
        'Hours are set by Cecurt, the state body that runs the park: Monday 5:00–11:00 (maintenance day), Tuesday to Saturday 5:00–22:30 and Sunday 5:00–18:00. For more about the park, see our <a href="/parque-tangamanga">Parque Tangamanga guide</a>.',
      ],
      fact: [
        ['trailhead', 'Av. Salvador Nava Martínez 3055'],
        ['drive', 'About 4 km / 5 min'],
        ['stats', 'Paved loop of 12.7 km, ~114 m gain; shorter loops are easy to improvise'],
        ['difficulty', 'Easy · stroller and wheelchair friendly'],
        ['fee', 'Free'],
        ['google', 'Google 4.8★ (8,881) · AllTrails 4.8★ (385)'],
      ],
    },
    canada: {
      title: 'Cañada del Lobo',
      paragraphs: [
        'The best family nature walk near the city. A small reservoir sits in a canyon between two hills, with herons and cormorants on the water, oaks and pinyon pines on the slopes and the little chapel of the Virgen del Chorrito. The easy walk around the dam is about 3.5 km with barely 40 m of climbing, and AllTrails reviewers call it suitable for children; a longer loop of 7.1 km adds some hills.',
        'Access is free and the parking lot is large. Two cautions: the trails are shared with mountain bikes, ATVs and jeeps, and a July 2026 review reported a car stereo stolen from the lower parking area, so park up near the dam and leave nothing visible.',
      ],
      fact: [
        ['drive', 'About 9 km / 12 min'],
        ['stats', '3.5 km (+40 m) dam walk; 7.1 km (+134 m) longer loop'],
        ['difficulty', 'Easy · dogs on leash'],
        ['fee', 'Free'],
        ['google', 'Google 4.6★ (273) · AllTrails 4.9★ (10)'],
      ],
    },
    piedrota: {
      title: 'La Piedrota',
      paragraphs: [
        'The easiest “real” hike in the Sierra de San Miguelito: a walk through nopal, biznaga and maguey scrub to a giant boulder with views back over the city. It is a favourite for sunset, so bring a headlamp for the way down. The informal access starts at the top of Avenida Chapultepec, near Privada El Pedregal; it can look blocked, but it is widely used, and painted arrows guide you most of the way.',
        'There is no shade at all, so avoid midday. <strong>Dog owners take note:</strong> in July and August 2025 poisoned bait killed at least one dog on this trail, and other poisonings were reported in the sierra that year. No 2026 cases turned up, but keep dogs leashed and don’t let them eat anything.',
      ],
      fact: [
        ['drive', 'About 11 km / 15 min'],
        ['stats', '6–8.2 km out and back, ~226 m gain'],
        ['difficulty', 'Easy–moderate'],
        ['fee', 'Free'],
        ['google', 'Google 4.8★ (75) · AllTrails 4.8★ (105)'],
      ],
    },
    original: {
      title: 'Cerro El Original (Santa María del Río)',
      paragraphs: [
        'A short, steep climb above Santa María del Río, the town famous for its silk rebozos. The hill was a Guachichil hunting ground and a hideout during the Revolution, and the top gives a full view of the town and valley. At 2.3 km round trip it takes about an hour, which makes it a perfect add-on to a day trip for shopping and lunch. The author of the main track calls it family-friendly but advises against going alone.',
      ],
      fact: [
        ['drive', 'About 50 km / 46 min via Highway 57 south'],
        ['stats', '2.3 km out and back, ~240 m gain, top at ~2,000 m'],
        ['difficulty', 'Easy–moderate'],
        ['fee', 'None found'],
        ['google', 'Google 4.7★ (130)'],
      ],
    },
    caballos: {
      title: 'Cerro y Cueva de los Caballos (Sierra de Álvarez)',
      paragraphs: [
        'The easiest way into the cool pine-oak forest of the Sierra de Álvarez, a federal protected area east of the city. At 2,500–2,650 m it is noticeably colder than SLP, with fog on winter mornings. The route follows a wide path up past the microwave antennas to a cave, close to the strange rock formations of the Valle de los Fantasmas: the Elephant Rock and the Piedra Flotante.',
        'Wildlife includes white-tailed deer, ringtails and acorn woodpeckers, and CONANP has recorded a puma on camera traps. A small entry fee was MXN 10 per person in December 2024 (dogs free). Much of the land around the rock formations is fenced, and map apps get confused, so ask locals in San Francisco or hire a local guide. Rattlesnakes live here; watch your step in warm months.',
      ],
      fact: [
        ['drive', 'About 45 km / 50 min via Highway 70 toward Rioverde'],
        ['stats', '~8 km loop or out-and-back, 240–330 m gain, max ~2,650 m'],
        ['difficulty', 'Easy–moderate · good for beginners and dogs'],
        ['fee', 'About MXN 10 per person (December 2024)'],
        ['google', 'Google 4.8★ (190)'],
      ],
    },
    joya: {
      title: 'Cráter Joya Honda',
      paragraphs: [
        'A dry volcanic crater about 1.4 km across and some 300 m deep, protected as a state natural monument. The hike circles the rim for about 5–6 km with big views into the crater, and wooden stairs lead down inside. Part of the loop has no defined path, with brush, loose rock and stone walls, and the rim is very windy.',
        'Access is via Highway 57 north to Estación Ventura (km 33), then about 5 km of dirt road. In 2024 entry was MXN 25 (MXN 300 to camp inside), with dry toilets and gorditas on weekends; a 2025 review describes the facilities as a little neglected.',
      ],
      fact: [
        ['drive', 'About 42 km / 65 min, last 5 km on dirt'],
        ['stats', '5.1–5.8 km rim loop, ~240 m gain'],
        ['difficulty', 'Moderate'],
        ['fee', 'MXN 25 entry (2024)'],
        ['google', 'Google 4.7★ (149)'],
      ],
    },
    capitan: {
      title: 'Sendero del Capitán (Cerro de San Pedro to Armadillo)',
      paragraphs: [
        'A signposted historic route of about 19 km along old mining and mule paths, linking three towns tied to Captain Miguel Caldera: Cerro de San Pedro, Monte Caldera and Armadillo de los Infante. It starts at about 2,040 m, rises to 2,200 m and drops to Armadillo at about 1,630 m, through yucca and oak country with almost no phone signal. The full route is point to point, so you need a car shuttle or a pickup.',
        'Families don’t need to do it all. From Cerro de San Pedro, a 3.3 km path climbs to the stone chapel of the Virgen del Encino, and an easy 7.3 km loop links the lookout and the church. Combine either with lunch in the half-abandoned mining town and its view over the open-pit mine. Civitatis runs a full-day guided version with an English or Spanish guide.',
      ],
      fact: [
        ['trailhead', 'Parking in Cerro de San Pedro'],
        ['drive', 'About 23 km / 28 min to the start; Armadillo is about 52 min from SLP'],
        ['stats', '~19–20 km one way, ~320 m up and ~700 m down'],
        ['difficulty', 'Moderate–hard (length); short sections easy'],
        ['fee', 'No trail fee found; the Cerro de San Pedro lookout charged MXN 20 (2025)'],
        ['google', 'Google 4.8★ (100) · AllTrails 4.8★ (21)'],
      ],
    },
    cerroGrande: {
      title: 'Cerro Grande (Suspiro Picacho, Mexquitic)',
      paragraphs: [
        'Described by local hikers as the highest point of Mexquitic de Carmona, at the north-western end of the Sierra de San Miguelito: a steep, stony climb to a wooded summit with views across the valley. The route is marked with lime and reaches about 2,565–2,600 m by GPS (the community cites 2,200 m). Trekking poles help on the loose descent.',
        'This is a community-protected hill and an important water-recharge area. <strong>Ask permission from the community authority in Suspiro Picacho before you go</strong>; a 2024 review says you need a permit, a May 2026 review says access became stricter after a suspected arson fire, and a July 2026 review suggests checking in at a village shop so the community judge is informed. Don’t build cairns, and carry out your rubbish.',
      ],
      fact: [
        ['trailhead', 'Suspiro Picacho village'],
        ['drive', 'About 19 km / 22 min'],
        ['stats', '11.3–11.9 km out and back, 540–600 m gain'],
        ['difficulty', 'Moderate–hard'],
        ['fee', 'None reported; permission required'],
      ],
    },
    ventana: {
      title: 'La Ventana (Sierra de San Miguelito)',
      paragraphs: [
        'The signature hike of San Luis Potosí. La Ventana (“the window”) is a natural rock arch near one of the highest points of the Sierra de San Miguelito, reached through oak and pine woodland from the community of La Amapola. The route is marked with ribbons and blue and white paint, and finishes with a steep rock scramble up to the arch, so it isn’t for small children. A detour of about 1 km each way leads to Cerro de la Cruz, with an altar to the Virgin of Guadalupe.',
        'Getting there is part of the adventure: from Highway 80 toward Guadalajara, turn off toward El Mezquital and drive about 10 km of rough dirt road; a high-clearance car is recommended. The ejido charges <strong>MXN 50 per person</strong> (confirmed in 2026) and watches your car. Pay only at the ejido parking area. Start early, carry at least 3 litres of water and download the track: in February 2025 a hiker went missing near this route after taking an alternate path.',
      ],
      fact: [
        ['trailhead', 'La Amapola (ejido parking)'],
        ['drive', 'About 43 km / 70 min, the last ~10 km on rough dirt'],
        ['stats', '12.2–12.6 km out and back, ~500 m gain, max ~2,820 m'],
        ['difficulty', 'Hard (final scramble)'],
        ['fee', 'MXN 50 per person (2026)'],
        ['google', 'Google 4.9★ (101) · AllTrails 4.6★ (42)'],
      ],
    },
    potosi: {
      title: 'Cerro del Potosí (Sierra de San Miguelito)',
      paragraphs: [
        'The city’s classic big day out. From the end of Avenida Chapultepec, a long, steady climb leads to a summit cross at about 2,650 m, where a visitors’ logbook is tucked into the base and the whole city spreads out below. Its most-used Wikiloc track has been recorded more than 840 times. After a rock painted “PB”, follow blue and orange marks; expect loose rock, steady grade and, according to one track author, a narrow exposed section with drops on both sides.',
        'There is almost no shade, so start at dawn and carry 4–6 litres of water, as one local track author recommends. Phone signal works on most of the route. Note the name again: this is not Nuevo León’s 3,700 m Cerro Potosí.',
      ],
      fact: [
        ['trailhead', 'End of Av. Chapultepec (or Soriana Chapultepec, adding ~4 km)'],
        ['drive', 'About 7 km / 10 min'],
        ['stats', '17.5–17.9 km out and back, 765–970 m gain, summit ~2,650 m'],
        ['difficulty', 'Hard'],
        ['fee', 'None reported'],
        ['google', 'Google 4.8★ (33) · AllTrails 4.8★ (79)'],
      ],
    },
    fraile: {
      title: 'Picacho del Fraile',
      paragraphs: [
        'The toughest climb on this list: a rugged route guided by cairns (some far apart) and blue and white paint, ending in a hands-on scramble over loose rock to a summit of about 2,800 m. An optional extension visits the remains of a small aircraft. Start from the plaza of El Terrero Sur or from Presa San Carlos, and beware of territorial dogs in the village. For experienced hikers only; there is no shade, and fires are not allowed.',
      ],
      fact: [
        ['trailhead', 'El Terrero Sur plaza or Presa San Carlos'],
        ['drive', 'About 18 km / 23 min'],
        ['stats', '~15.6 km out and back, ~960 m gain, max ~2,800 m'],
        ['difficulty', 'Hard (scramble)'],
        ['fee', 'None reported'],
        ['google', 'Google 4.8★ (14) · AllTrails 4.9★ (17)'],
      ],
    },
    quemado: {
      title: 'Cerro del Quemado (Real de Catorce)',
      paragraphs: [
        'High above Real de Catorce, the Cerro del Quemado is a sacred ceremonial site for the Wixárika (Huichol) people in Wirikuta, with stone altars, offerings and enormous views over the desert. The marked route (orange dots) is about 10.5 km round trip with 365–410 m of climbing, but the altitude, at about 2,940 m by GPS, makes it feel harder. Some websites claim 3,800 m; GPS data says otherwise.',
        'Respect is not optional: don’t touch offerings and stay quiet if a ceremony is under way. AllTrails lists access as free, but hikers, including one in 2024, report paying a MXN 20 maintenance contribution at the summit, so carry small change. Real de Catorce is about 3 h 30 min from the city, so stay the night; our <a href="/blog/real-de-catorce-guide-2026">Real de Catorce guide</a> covers the rest of the trip.',
      ],
      fact: [
        ['drive', 'About 213 km / 3 h 30 min, plus the Ogarrio tunnel'],
        ['stats', '10.3–10.9 km out and back, 365–410 m gain, max ~2,940 m'],
        ['difficulty', 'Moderate (high altitude)'],
        ['fee', 'Free per AllTrails; some hikers report a MXN 20 contribution'],
        ['google', 'Google 4.8★ (78) · AllTrails 4.9★ (39)'],
      ],
    },
  },
  leftOut: {
    title: 'Trails left off the list (and why)',
    subtitle: 'Some are good, just not the best choice in 2026',
    rows: [
      ['Presa de San José', '2026 reviews describe the dam area as vandalised and dirty; the trail is shared with motocross and the creek bed can flash-flood.'],
      ['Cañón del Chivo (Sierra de Álvarez)', 'Unmarked boulder-hopping canyon with flash-flood risk and car break-ins reported; go only with a guide.'],
      ['Cerro San Miguelito and La Campana', 'Good routes, but they overlap with La Piedrota and Cerro del Potosí.'],
      ['Parque Nacional El Gogorrón', 'No reliable trail data or fees could be confirmed.'],
    ],
  },
  seasons: {
    title: 'Altitude, seasons and water',
    subtitle: 'Why every local hiker starts at first light',
    paragraphs: [
      'SLP city sits at about 1,860 m. Trailheads in the Sierra de San Miguelito are at about 1,900–2,400 m and summits reach 2,600–2,880 m; the Sierra de Álvarez sits around 2,500–2,650 m, and Real de Catorce at 2,600–3,200 m. If you’ve just arrived, take the first few days easy, drink more than you think and remember that sunburn comes faster at altitude.',
      'The best months are <strong>October to March</strong>: dry, cool and clear, with September and October greenest right after the rains. December and January bring near-freezing dawns at the higher trailheads and, occasionally, snow. April and May are hot (May averages a 28 °C high) and are the peak of wildfire season. From June to September, afternoon storms bring lightning on exposed summits, slippery rock and flash floods in canyons.',
      'There is no water on these trails and very little shade. Plan on half a litre per hour, at least 3 litres on summit days, plus electrolytes, a hat, long sleeves and sunscreen.',
    ],
  },
  safety: {
    title: 'Safety: what actually goes wrong',
    subtitle: 'Getting lost is the real risk, not crime on the trail',
    paragraphs: [
      'Searches of local and national news found no 2025–2026 reports of armed assaults on hikers on the trails in this guide. What did show up: <strong>hikers getting lost</strong>. By early March 2026, six hikers had already needed rescue in the state, in Armadillo de los Infante, Real de Catorce and the Sierras of San Miguelito and Álvarez, and the head of State Civil Protection said most didn’t know the route or had separated from their group.',
      'The other problems are smaller but real: car break-ins at some trailheads, the 2025 dog poisonings around La Piedrota, and a 2022 report of a man charging a fake “toll” near La Amapola. The US State Department rates San Luis Potosí state at Level 2, “exercise increased caution” (May 2026).',
      'The fixes are simple: hike with others, download the track before you leave signal, tell someone your route, keep the group together, park where other hikers park, leave nothing visible in the car, pay fees only at the official community parking, and be off remote trails before dusk. In an emergency, call <strong>911</strong>.',
    ],
  },
  rules: {
    title: 'Rules in the protected areas',
    subtitle: 'Most of these trails cross federal reserves or community land',
    paragraphs: [
      'The Sierra de San Miguelito became a federal Flora and Fauna Protection Area in December 2021, covering 111,160 hectares across SLP, Mexquitic, Villa de Reyes and Villa de Arriaga. Its management rules, published in the DOF in June 2024, ask hikers to stay on established trails, carry out all rubbish, keep dogs on a leash and pick up after them, and only light fires where allowed. The Sierra de Álvarez has similar CONANP rules.',
      'Much of the land is ejido or community property (La Amapola, Suspiro Picacho, the Valle de los Fantasmas). Small fees and requests for permission are normal and legitimate when they come from the community authority or the official parking area. Respect fences and gates.',
    ],
  },
  guides: {
    title: 'Hiking clubs and guides',
    subtitle: 'The easiest way to learn the trails safely',
    paragraphs: [
      'If you’re new to the area, the simplest way in is a group hike. <strong>Spot San Luis</strong> runs community hikes on Saturday and Sunday mornings with certified guides (NOM-09-TUR-2002), with groups capped at 30 and some free routes. <strong>Club de Senderismo Expeditions</strong> organises regular outings, and <strong>Corazón de Xoconostle</strong> offers certified guides, insurance and transport for treks in the Sierra de Álvarez, San Miguelito and beyond. For the Sendero del Capitán, Civitatis sells a full-day guided tour with hotel pickup.',
    ],
  },
  proTips: [
    ['Start at first light', 'Every major trail’s reviews say the same: afternoons are hot, and finishing in the dark is how people get lost.'],
    ['Download the track', 'Marking is informal (paint, lime, ribbons, cairns). Save the Wikiloc or AllTrails track offline before you leave signal.'],
    ['Carry more water than you think', 'Half a litre per hour, 3 litres minimum on summits, 4–6 litres for Cerro del Potosí.'],
    ['Protect your dog', 'Leash it in the protected areas, don’t let it eat anything on the trail, and watch for rattlesnakes in warm months.'],
    ['Respect community land', 'Pay small fees only at official parking, ask permission where it’s expected and close gates behind you.'],
    ['Acclimatise first', 'Do Tangamanga or Cañada del Lobo before a 2,800 m summit if you’ve just arrived from sea level.'],
  ],
  takeaways: [
    'La Ventana is the signature hike: a rock arch at about 2,800 m, 12 km round trip, MXN 50 per person.',
    'Cerro del Potosí is the big summit you can start from the end of Avenida Chapultepec.',
    'Families should start with Cañada del Lobo, Tangamanga I or the short paths from Cerro de San Pedro.',
    'Go October to March, start at dawn and carry at least 3 litres of water on summit days.',
    'Getting lost is the main risk: hike with others, download the track and stay together.',
  ],
  faq: [
    ['What is the best hike in San Luis Potosí?', 'La Ventana, a natural rock arch at about 2,800 m in the Sierra de San Miguelito. The route from La Amapola is 12.2–12.6 km round trip with about 500 m of climbing and a final scramble. The ejido charges MXN 50 per person (2026).'],
    ['Are there easy hikes for kids in San Luis Potosí?', 'Yes. Cañada del Lobo has a 3.5 km loop around a small dam with only 40 m of climbing, and Parque Tangamanga I has free paved loops of up to 12.7 km. The short paths from Cerro de San Pedro and Cerro El Original in Santa María del Río also suit families.'],
    ['Is it safe to hike around San Luis Potosí?', 'No 2025–2026 reports of armed assaults on hikers turned up for these trails. The main risk is getting lost: six hikers needed rescue in the state by March 2026. Hike in groups, download the track and avoid dusk on remote trails.'],
    ['What is the best time of year to hike in San Luis Potosí?', 'October to March, when it is dry, cool and clear. April and May are hot, and June to September brings afternoon storms and lightning on exposed summits.'],
    ['Is Cerro del Potosí the same as Cerro Potosí in Nuevo León?', 'No. The Cerro del Potosí near San Luis Potosí city is about 2,650 m high in the Sierra de San Miguelito. Cerro Potosí in Nuevo León is a different mountain of about 3,700 m.'],
    ['Do I need to pay to hike in San Luis Potosí?', 'Most city trails are free, including Tangamanga I, Cañada del Lobo, La Piedrota and Cerro del Potosí. Community-run trailheads charge small fees, such as MXN 50 per person at La Ventana. Pay only at the official parking area.'],
  ],
  related: [
    ['/blog/family-camping-near-san-luis-potosi', 'Best Family Camping Near San Luis Potosí', 'Where to sleep under the stars in the same sierras'],
    ['/blog/real-de-catorce-guide-2026', 'Real de Catorce Guide', 'Everything you need for the trip to Cerro del Quemado'],
    ['/blog/day-trips-from-san-luis-potosi-2026', 'Day Trips from San Luis Potosí', 'Pair a hike with a town: Cerro de San Pedro, Santa María del Río and more'],
    ['/parque-tangamanga', 'Parque Tangamanga', 'The city’s big park, for warm-up walks and runs'],
  ],
  captions: {
    tangamangaLake: 'The main lake of Parque Tangamanga I, the easiest place to walk or run in the city.',
    tangamangaTrees: 'Late afternoon in Tangamanga I. The park closes at 22:30 Tuesday to Saturday.',
    santaMaria: 'The hills above Santa María del Río, where Cerro El Original makes a short climb.',
    alvarez: 'Pine-oak forest in the Sierra de Álvarez, near the Valle de los Fantasmas.',
    sanPedroStreet: 'Cerro de San Pedro, the old mining town where the Sendero del Capitán begins.',
    sanPedroMine: 'Cerro de San Pedro and the open-pit mine behind it.',
    arch: 'Natural rock arches are the reward on the sierra’s harder routes.',
    snow: 'Snow on Cerro de San Pedro. Winter dawns can drop below freezing at the trailheads.',
    quemado: 'Wixárika crafts on the summit of the Cerro del Quemado, a sacred site above Real de Catorce.',
  },
};
